# tasks file for install-packages
---
  - name: Update apt cache and make sure Vim, Curl and Unzip are installed
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
      - neovim
      - curl
      - unzip
      - vlc
      - tree
      - samba
      - openssh-server
      - htop

